name: Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Create
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin jq
          ./create_json.sh

      - name: Commit changed data
        run: |
          if git diff --quiet -- data; then
            echo "No data changes."
            exit 0
          fi

          git config user.name "kvie-bot"
          git config user.email "open@kreis-viersen.de"

          git add data
          git commit -m "Update JSON"
          git push
